### ISSUE TITLE
Import commits from apache/arrow

### ISSUE THREAD

**Issue by kou** [apache/arrow-go#1]
We need only commits for https://github.com/apache/arrow/tree/main/go . Other commits such as commits for `.github/` aren't needed. We need to adjust other files for this repository.

We can do this by the following command lines:

```bash
git clone git@github.com:apache/arrow-go.git
cd arrow-go
git remote add arrow https://github.com/apache/arrow.git
git fetch arrow
git switch -c arrow-main-go arrow/main
git filter-branch --subdirectory-filter go
git switch main
git rebase arrow-main-go
git push origin --force main
```

**Comment by raulcd** [comment]
I've tested the commands locally (without the push obviously) and the repository looks good on a first check. Should we run some testing to validate functionality before pushing?

**Comment by joellubi** [comment]
> Hmm. It seems that we misses some files. (There are some "[no test files]".)

This doesn't necessarily mean we missed files, not all directories contain test files. I've confirmed I get the same test output running on `apache/arrow:main`.

**Comment by kou** [comment]
Thanks. I didn't know about it.

**Comment by zeroshade** [comment]
This LGTM, we can do a follow-up PR that will update all of the import paths across the code-base to the new URL

**Comment by kou** [comment]
Thanks for confirming this approach. I'll do it soon.

FYI: Here are related issues:

> BTW we should track if there is any new commit being pushed to the main arrow repo on the go side to manually cherry-pick it in the interim.

https://github.com/apache/arrow/issues/43881  [Go] Notify apache/arrow-go migration to all open PRs

> we can do a follow-up PR that will update all of the import paths across the code-base to the new URL

#4 Update package name

**Comment by kou** [comment]
Sorry. I haven't done this yet.
I'll do this now.

**Comment by kou** [comment]
We need to remove the protected branch configuration in `.asf.yaml`:

```console
$ git push origin --force-with-lease main
Enumerating objects: 13921, done.
Counting objects: 100% (13921/13921), done.
Delta compression using up to 24 threads
Compressing objects: 100% (3993/3993), done.
Writing objects: 100% (13921/13921), 13.79 MiB | 2.75 MiB/s, done.
Total 13921 (delta 9809), reused 13212 (delta 9721), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (9809/9809), done.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Cannot force-push to this branch
To github.com:apache/arrow-go.git
 ! [remote rejected]     main -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:apache/arrow-go.git'
```

**Comment by kou** [comment]
I tried `git cherry-pick arrow-main-go` instead of `git merge` to avoid force push. But it causes conflicts...

Can we enable force push temporary? #80

**Comment by kou** [comment]
Oh, `(git log --format=%H --reverse arrow-main-go | while read commit; do git cherry-pick $commit; done)` works without conflict. I'll push it without #80.

**Comment by kou** [comment]
Pushed!
