### ISSUE TITLE
Add test CI for arm Runners

### ISSUE THREAD

**Issue by raulcd** [apache/arrow-go#107]
We have some jobs that run on ARM self-hosted runners, we should also add those: https://github.com/apache/arrow/blob/main/.github/workflows/go.yml#L80-L91

I've created a JIRA issue asking INFRA to add this repository to the runner group so we can use the self-hosted runners that we share with the rest of repositories (arrow, arrow-nanoarrow and arrow-adbc): https://issues.apache.org/jira/browse/INFRA-26098

**Comment by kou** [comment]
Thanks!

FYI: We may be able to use GitHub hosted Arm runner in this year: https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by raulcd** [comment]
Yes, as soon as they are available we should migrate the existing jobs that use self-hosted arm runners.
