### ISSUE TITLE
SIGSEV on zero length arrow array

### ISSUE THREAD

**Issue by ukclivecox** [apache/arrow-go#191]
### Describe the bug, including details regarding any error messages, version, and platform.

The fix done by https://github.com/apache/arrow-go/pull/175 seems to cause a SIGSEV after code returning when 0 length data spotted at:

https://github.com/apache/arrow-go/blob/d10a8591351fd113fe7ae90c9b56e80ebdfd196d/arrow/cdata/exports.go#L164

Does some cleanup or other work need to be done like for example:

https://github.com/apache/arrow-go/blob/d10a8591351fd113fe7ae90c9b56e80ebdfd196d/arrow/cdata/cdata_exports.go#L467-L468

### Component(s)

Other

**Comment by hsight** [comment]
This maybe an issue in my tests as arrow record had already been released. Would need to create a test case to validate if fix is ok in empty record scenario. Will close for now.

**Comment by ukclivecox** [comment]
This maybe an issue in my tests as arrow record had already been released. Would need to create a test case to validate if fix is ok in empty record scenario. Will close for now.
