### ISSUE TITLE
Transfer Go related open issues from apache/arrow

### ISSUE THREAD

**Issue by kou** [apache/arrow-go#25]
Can we use an existing script for this? Or should we create it?

**Comment by assignUser** [comment]
There is no way to do it via the web ui (only for single issues) but the gh cli can do it  `gh issue transfer` so that should be easily combined with xargs and a query to list the go labeled issues to do it.

**Comment by assignUser** [comment]
I just tested it and issue numbers will be reset to the target repos. This means that the link between commit message and issue will break without a way to reconstruct it. The existing GH-123 links will ofc also break within arrow-go but can still be found in arrow if the issues still exist. So m

aybe we should only move over open issues so closed issues keep their numbers? @zeroshade

**Comment by kou** [comment]
Ah, good point. Let's transfer only opened issues. (Let's keep closed issues in apache/arrow.)

**Comment by assignUser** [comment]
There is actually only 60 issues, I will curate the actual list and add the labels (like good-first-issue) to this repo, as otherwise they get dropped. And then transfer this issues if there are no objections.

**Comment by zeroshade** [comment]
Thanks everyone, sounds great! I'll go over them afterwards and see if there's any other labels we want to add etc.

**Comment by assignUser** [comment]
Done!
```
gh issue list --label "Component: Go" --state "open" -L 100 --json 'number,labels'  > issues.json
 jq -r '[.[].number] -  [34975, 17255, 21688, 20390, 32712] | map(select(. < 43605)) | .[]' issues.json |  xargs -I% gh issue transfer % https://github.com/apache/arrow-go
```
(I obviously did not add the component: go label^^)

**Comment by kou** [comment]
Thanks.
I close this. If there are any more follow-up tasks, let's create a new issue.
