### ISSUE TITLE
Prepare Docker based test system

### ISSUE THREAD

**Issue by kou** [apache/arrow-go#8]
apache/arrow uses Archery: https://github.com/apache/arrow/tree/main/dev/archery

Do we keep using Archery? Can we use Docker (including `docker compose`) directly?

**Comment by raulcd** [comment]
From what I can see on the [tasks definition](https://github.com/apache/arrow/blob/main/dev/tasks/tasks.yml#L1479) there are only a couple of go tests there. We can probably add those as part of the PR based CI and remove archery completely from arrow-go.

**Comment by kou** [comment]
We'll use `docker compose`.
